### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by benjscohen** [klout/opendata#6]
When I try to run `./run` I get the following type error:

`TypeError: Expected int32, got <tf.Variable 'lstm_1_W_i:0' shape=(128, 32) dtype=float32_ref> of type 'Variable' instead.`

When I run the python script `predict_single_open.py` I get the same error.

**Comment by benjscohen** [comment]
Here is the full output:

Benjamins-MacBook-2:democrat_republican_by_list_20160816_1M_sample_open_data benjscohen$ python predict_single_open.py
Using TensorFlow backend.
Loading model from path /Users/benjscohen/Google Drive/harvard/Junior Year/Spring/ER 43/er43Final/democrat_republican_by_list_20160816_1M_sample_open_data/ 
Loading architecture from /Users/benjscohen/Google Drive/harvard/Junior Year/Spring/ER 43/er43Final/democrat_republican_by_list_20160816_1M_sample_open_data/architecture.json.
{"loss": "binary_crossentropy", "optimizer": {"epsilon": 1e-08, "lr": 0.0010000000474974513, "name": "RMSprop", "rho": 0.8999999761581421}, "class_name": "Sequential", "keras_version": "1.0.4", "config": [{"class_name": "Embedding", "config": {"trainable": true, "name": "embedding_1", "activity_regularizer": null, "W_constraint": null, "init": "uniform", "input_dtype": "int32", "mask_zero": false, "input_dim": 40000, "batch_input_shape": [null, 40], "W_regularizer": null, "dropout": 0.0, "output_dim": 128, "input_length": 40}}, {"class_name": "LSTM", "config": {"U_regularizer": null, "name": "lstm_1", "inner_activation": "hard_sigmoid", "go_backwards": false, "activation": "tanh", "trainable": true, "unroll": false, "consume_less": "cpu", "stateful": false, "init": "glorot_uniform", "inner_init": "orthogonal", "dropout_U": 0.0, "dropout_W": 0.0, "input_dim": 128, "return_sequences": false, "b_regularizer": null, "W_regularizer": null, "output_dim": 32, "forget_bias_init": "one", "input_length": null}}, {"class_name": "Dropout", "config": {"p": 0.5, "trainable": true, "name": "dropout_1"}}, {"class_name": "Dense", "config": {"W_constraint": null, "b_constraint": null, "name": "dense_1", "activity_regularizer": null, "trainable": true, "init": "glorot_uniform", "bias": true, "input_dim": null, "b_regularizer": null, "W_regularizer": null, "activation": "sigmoid", "output_dim": 1}}], "sample_weight_mode": null}
2018-04-10 19:37:12.454933: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-10 19:37:12.454977: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-10 19:37:12.455082: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-04-10 19:37:12.455092: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-04-10 19:37:12.455102: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "predict_single_open.py", line 166, in <module>
    main()
  File "predict_single_open.py", line 138, in main
    model, tokenizer = load_model_tokenizer(args)
  File "predict_single_open.py", line 116, in load_model_tokenizer
    model = load_model(model_folder, args.architectureFileName, args.weightsFileName)
  File "predict_single_open.py", line 92, in load_model
    model = model_from_json(config)
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/keras/models.py", line 36, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/keras/utils/layer_utils.py", line 35, in layer_from_config
    return layer_class.from_config(config['config'])
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/keras/models.py", line 784, in from_config
    model.add(layer)
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/keras/models.py", line 145, in add
    output_tensor = layer(self.outputs[0])
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/keras/engine/topology.py", line 458, in __call__
    self.build(input_shapes[0])
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/keras/layers/recurrent.py", line 728, in build
    self.W = K.concatenate([self.W_i, self.W_f, self.W_c, self.W_o])
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 475, in concatenate
    return tf.concat(axis, tensors)
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/benjscohen/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got <tf.Variable 'lstm_1_W_i:0' shape=(128, 32) dtype=float32_ref> of type 'Variable' instead.

**Comment by benjscohen** [comment]
I am using python 3.6, and have installed the modules in the version specified.
